<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <title><?php echo $this->__('Email Preview'); ?></title>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('mk-mailprev.css') ?>">
    </head>
    <body>
        <?php echo $this->getChildHtml('headerbar') ?>
        <?php echo $this->getChildHtml('content') ?>
        <?php echo $this->getChildHtml('profiler') ?>
    </body>
</html>
